# Generated by Django 3.1.2 on 2020-10-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='introduce',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
