# Generated by Django 3.1.2 on 2020-10-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_customuser_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='introduce',
            field=models.CharField(max_length=500),
        ),
    ]
