# Generated by Django 3.1.1 on 2020-09-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_socialplatform_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
