# Generated by Django 3.0.8 on 2020-09-08 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_socialplatform_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='대댓글')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoms', to='appname.Comment')),
                ('rc_writer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='rc_writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
