# Generated by Django 3.0.8 on 2020-09-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0004_recomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=50, verbose_name='댓글'),
        ),
    ]
