# Generated by Django 2.2.8 on 2020-09-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0005_auto_20200908_2127'),
        ('appname', '0004_auto_20200908_1934'),
    ]

    operations = [
    ]
