# Generated by Django 3.1.1 on 2020-10-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0008_auto_20201004_1751'),
        ('appname', '0005_summernote'),
    ]

    operations = [
    ]
