# Generated by Django 3.1.1 on 2020-09-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0008_auto_20200917_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meet_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.TextField(blank=True),
        ),
    ]
