# Generated by Django 3.1.1 on 2020-09-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0009_auto_20200922_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.TextField(blank=True),
        ),
    ]
