# Generated by Django 2.2.8 on 2020-10-13 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0009_merge_20201005_2008'),
        ('appname', '0009_merge_20201009_1600'),
    ]

    operations = [
    ]
