# Generated by Django 3.1.1 on 2020-10-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0009_merge_20201005_2008'),
        ('appname', '0004_auto_20201009_1617'),
    ]

    operations = [
    ]
