# Generated by Django 3.1.1 on 2020-09-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0010_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='max_p',
            field=models.TextField(blank=True),
        ),
    ]
