# Generated by Django 3.1.1 on 2020-09-22 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0011_post_max_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='now_p',
            field=models.ManyToManyField(related_name='now_p', to=settings.AUTH_USER_MODEL),
        ),
    ]
