# Generated by Django 3.1.1 on 2020-09-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0012_post_now_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rule',
            field=models.TextField(blank=True),
        ),
    ]
