# Generated by Django 3.1.1 on 2020-09-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0013_post_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='max_p',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='meet_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='place',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
