# Generated by Django 3.1.1 on 2020-09-29 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0015_remove_post_now_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
    ]
