# Generated by Django 3.1.1 on 2020-09-29 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0018_auto_20200929_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='view',
        ),
        migrations.AddField(
            model_name='post',
            name='view',
            field=models.ManyToManyField(related_name='view', to=settings.AUTH_USER_MODEL),
        ),
    ]
