# Generated by Django 3.1.2 on 2020-10-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0021_post_like_count'),
        ('appname', '0010_merge_20201009_1627'),
    ]

    operations = [
    ]
