# Generated by Django 3.1.1 on 2020-10-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0010_merge_20201009_1627'),
        ('appname', '0021_post_like_count'),
        ('appname', '0010_merge_20201013_1840'),
    ]

    operations = [
    ]
