# Generated by Django 3.1.1 on 2020-10-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0022_merge_20201013_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='max_p',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meet_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meet_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='member',
        ),
        migrations.RemoveField(
            model_name='post',
            name='place',
        ),
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='post',
            name='view',
        ),
    ]
