# Generated by Django 3.1.2 on 2020-10-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0022_merge_20201020_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='max_p',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meet_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meet_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='member',
        ),
        migrations.RemoveField(
            model_name='post',
            name='place',
        ),
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='post',
            name='view',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
