# Generated by Django 3.1.1 on 2020-10-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0023_auto_20201013_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
