# Generated by Django 3.1.1 on 2020-10-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0024_remove_post_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
