# Generated by Django 3.1.1 on 2020-10-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0025_post_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
