# Generated by Django 3.1.1 on 2020-10-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0026_auto_20201020_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
