# Generated by Django 3.1.1 on 2020-10-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0027_remove_post_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sort',
            field=models.TextField(default='정렬방식'),
        ),
    ]
