# Generated by Django 3.1.1 on 2020-10-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0028_post_sort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sort',
        ),
    ]
