# Generated by Django 2.2.8 on 2020-09-07 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0007_book_bookname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='img',
        ),
    ]
