# Generated by Django 2.2.8 on 2020-09-07 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0008_remove_question_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='opt5',
        ),
    ]
