# Generated by Django 2.2.8 on 2020-09-07 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0009_remove_question_opt5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Plink',
        ),
        migrations.RemoveField(
            model_name='book',
            name='bookname',
        ),
        migrations.RemoveField(
            model_name='book',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='book',
            name='poem',
        ),
        migrations.RemoveField(
            model_name='book',
            name='poet',
        ),
    ]
