# Generated by Django 2.2.8 on 2020-09-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0011_remove_book_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tester',
            old_name='Antiseptic',
            new_name='Collect',
        ),
        migrations.RenameField(
            model_name='tester',
            old_name='Bada',
            new_name='Control',
        ),
        migrations.RenameField(
            model_name='tester',
            old_name='Because',
            new_name='Cooking',
        ),
        migrations.RenameField(
            model_name='tester',
            old_name='Blackleaf',
            new_name='Exercise',
        ),
        migrations.RenameField(
            model_name='tester',
            old_name='Fifteen',
            new_name='Leisure',
        ),
        migrations.RenameField(
            model_name='tester',
            old_name='Jangma',
            new_name='Making',
        ),
        migrations.RenameField(
            model_name='tester',
            old_name='Kind',
            new_name='Music',
        ),
        migrations.RenameField(
            model_name='tester',
            old_name='Lofi',
            new_name='Photos',
        ),
        migrations.RenameField(
            model_name='tester',
            old_name='Love',
            new_name='Reading',
        ),
        migrations.RenameField(
            model_name='tester',
            old_name='Math',
            new_name='Travel',
        ),
        migrations.RemoveField(
            model_name='tester',
            name='Meehee',
        ),
        migrations.RemoveField(
            model_name='tester',
            name='Nowrite',
        ),
        migrations.RemoveField(
            model_name='tester',
            name='Possible',
        ),
        migrations.RemoveField(
            model_name='tester',
            name='Small',
        ),
        migrations.RemoveField(
            model_name='tester',
            name='Sobolo',
        ),
        migrations.RemoveField(
            model_name='tester',
            name='Station',
        ),
        migrations.AlterField(
            model_name='question',
            name='opt3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt4',
            field=models.TextField(),
        ),
    ]
