# Generated by Django 3.1.1 on 2020-10-20 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='meet_writer',
            new_name='username',
        ),
    ]
