# Generated by Django 3.1.2 on 2020-10-24 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='member',
        ),
        migrations.RemoveField(
            model_name='item',
            name='other_id',
        ),
        migrations.AddField(
            model_name='order',
            name='member',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='other_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
